import os
import json
from collections import Counter
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from typing import Optional

app = FastAPI(title="Bursa LULC API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000"], 
    allow_credentials=False, 
    allow_methods=["*"],
    allow_headers=["*"],
)

VALID_YEARS = [2020, 2025]

def load_classification_data(year: int):
    """Load raw tile classification JSON from disk."""
    # Look for the files generated by spatial_join.py
    file_path = f"classification_{year}_enriched.json"
    if not os.path.exists(file_path):
        raise HTTPException(
            status_code=404,
            detail=f"Data for {year} not found. Run spatial_join.py first."
        )
    with open(file_path, "r", encoding="utf-8") as f:
        return json.load(f)

def compute_stats(tiles: list) -> dict:
    """Aggregate tile predictions into class distribution percentages."""
    if not tiles:
        return {}

    class_counts = Counter(tile["predicted_class"] for tile in tiles)
    total = len(tiles)

    return {
        "total_tiles": total,
        "distribution": {
            cls: {
                "count": count,
                "percentage": round((count / total) * 100, 2)
            }
            for cls, count in sorted(class_counts.items())
        }
    }

def filter_tiles(data: dict, district: Optional[str] = None) -> list:
    """Filters tiles by district if a district is provided."""
    tiles = data.get("tiles", [])
    if district:
        # Only keep tiles that match the requested district
        tiles = [t for t in tiles if t.get("district") == district]
    return tiles

# --- Endpoints ---

@app.get("/")
def read_root():
    return {"message": "Bursa LULC API is running."}

@app.get("/api/map/{year}")
def get_map(year: int, district: Optional[str] = None):
    if year not in VALID_YEARS:
        raise HTTPException(status_code=400, detail=f"Year must be one of {VALID_YEARS}")
    
    data = load_classification_data(year)
    filtered_tiles = filter_tiles(data, district)
    return {"tiles": filtered_tiles}

@app.get("/api/stats/{year}")
def get_stats(year: int, district: Optional[str] = None):
    if year not in VALID_YEARS:
        raise HTTPException(status_code=400, detail=f"Year must be one of {VALID_YEARS}")
    
    data = load_classification_data(year)
    filtered_tiles = filter_tiles(data, district)
    return compute_stats(filtered_tiles)

@app.get("/api/change")
def get_change(district: Optional[str] = None):
    data_2020 = load_classification_data(2020)
    data_2025 = load_classification_data(2025)

    tiles_2020 = filter_tiles(data_2020, district)
    tiles_2025 = filter_tiles(data_2025, district)

    stats_2020 = compute_stats(tiles_2020)
    stats_2025 = compute_stats(tiles_2025)

    all_classes = set(stats_2020.get("distribution", {})) | set(stats_2025.get("distribution", {}))

    change = {}
    for cls in sorted(all_classes):
        pct_2020 = stats_2020.get("distribution", {}).get(cls, {}).get("percentage", 0.0)
        pct_2025 = stats_2025.get("distribution", {}).get(cls, {}).get("percentage", 0.0)
        change[cls] = {
            "2020": pct_2020,
            "2025": pct_2025,
            "delta": round(pct_2025 - pct_2020, 2)
        }

    return {"change_by_class": change}